### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Hubbotu** [DrOxlotus/CuratorClassic#2]
Hey. I made a translation into Russian.
https://github.com/Hubbotu/Curator-ClassicRU/blob/master/Locales.lua

**Comment by DrOxlotus** [comment]
Wow! Thanks a ton, @Hubbotu! It's been added to the table, and will be readily available in the next update.

**Comment by DrOxlotus** [comment]
Added to the latest release: 1.1.0.

Thanks again.
